name: Production CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ECR_REPOSITORY: network_assignment

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ecom-app .

      - name: Run Django Health Check
        run: |
          docker run --rm ecom-app python manage.py check

      - name: Tag Docker Image
        run: |
          docker tag ecom-app:latest ${{ steps.login-ecr.outputs.registry }}/network_assignment:prod-latest
          docker tag ecom-app:latest ${{ steps.login-ecr.outputs.registry }}/network_assignment:prod-${{ github.sha }}

      - name: Push Docker Images
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/network_assignment:prod-latest
          docker push ${{ steps.login-ecr.outputs.registry }}/network_assignment:prod-${{ github.sha }}

      - name: Check if Security Group exists
        id: check_sg
        run: |
          SG=$(aws ec2 describe-security-groups \
            --filters "Name=group-name,Values=network-assignment-sg" \
            --query "SecurityGroups[0].GroupId" \
            --output text)

          if [ "$SG" = "None" ] || [ -z "$SG" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Security Group exists: $SG"
          fi

      - name: Setup Terraform
        if: steps.check_ec2.outputs.exists == 'false'
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        if: steps.check_ec2.outputs.exists == 'false'
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        if: steps.check_ec2.outputs.exists == 'false'
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        if: steps.check_ec2.outputs.exists == 'false'
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create Inventory
        run: |
          echo "[web]" > ansible/inventory.ini
          echo "${{ secrets.EC2_HOST }}" >> ansible/inventory.ini

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ansible-playbook ansible/playbook.yml \
            -i ansible/inventory.ini \
            --private-key ~/.ssh/id_rsa \
            -u ubuntu \
            -e aws_region="${{ secrets.AWS_REGION }}" \
            -e ecr_repository="${{ secrets.ECR_REPOSITORY }}" \
            -e ecr_registry="${{ steps.login-ecr.outputs.registry }}" \
            -e image_tag="prod-latest"